/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ky_jni_NativeCalculator */

#ifndef _Included_com_ky_jni_NativeCalculator
#define _Included_com_ky_jni_NativeCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ky_jni_NativeCalculator
 * Method:    calc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ky_jni_NativeCalculator_calc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
