/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ky_jni_AacEncoder */

#ifndef _Included_com_ky_jni_AacEncoder
#define _Included_com_ky_jni_AacEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ky_jni_AacEncoder
 * Method:    convertToAac
 * Signature: ([BIIIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ky_jni_AacEncoder_convertToAac
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
